language: c
compiler:
  - clang
dist: trusty
matrix:
  include:
    - os: linux
      dist: xenial
      env:
        - CC="/usr/local/clang-7.0.0/bin/clang"
        - CXX="/usr/local/clang-7.0.0/bin/clang++"

# before_install: 
#   - eval "${MATRIX_EVAL}"
install: 
  - echo 'add_subdirectory(test)' >> CMakeLists.txt
before_script: 
  - cd build
  - cmake ..
script: 
  - make
  - ./test/TestHeap
if: tag IS present