language: c
compiler:
  - gcc
dist: trusty
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"


before_install: 
  - eval "${MATRIX_EVAL}"
install: 
  - echo 'add_subdirectory(test)' >> CMakeLists.txt
before_script: 
  - cd build
  - cmake ..
script: 
  - make
  - ./test/TestHeap